"""
i18n.py
--------
Minimal internationalization layer for the AWS Mock Exam Engine.

Usage:
    from i18n import t
    st.title(t("app_title"))
    st.success(t("pass_banner", pct=92.0, threshold=75))

`t(key, **kwargs)` looks up `key` in the dictionary for the currently selected
UI language (st.session_state.language, defaulting to "en"), falling back to
English if a key is missing in the target language, and finally to the raw
key itself if it's missing everywhere (so the UI never crashes on a missing
translation — it just shows the untranslated key, which is easy to spot and
fix).

Scope note: this covers the app's static interface text (labels, buttons,
headings, messages). It does not translate user-entered or AI-generated
question content, or raw error text returned by external libraries/APIs —
those are shown as-is regardless of the selected UI language.
"""

import streamlit as st

LANGUAGES = {"en": "English", "ja": "日本語"}
DEFAULT_LANGUAGE = "en"

TRANSLATIONS = {
    "en": {
        # --- App / navigation ---
        "app_title": "☁️ AWS Mock Exam Engine",
        "nav_label": "Navigation",
        "nav_help": "Switch between practicing exams and managing the question bank.",
        "nav_take_exam": "Take an Exam",
        "nav_admin": "Admin Dashboard",
        "language_label": "🌐 Language",

        # --- Exam configuration sidebar ---
        "exam_config_header": "Exam Configuration",
        "no_certs_found": "No certifications found in the database.",
        "target_cert_label": "Target Certification",
        "level_pass_mark": "Level: **{level}** | Pass mark: **{pct}%**",
        "questions_in_bank": "Questions available in bank: **{count}**",
        "question_source_header": "**Question Source**",
        "question_source_bank": "📚 Use Existing Question Bank",
        "question_source_ai": "🤖 Generate New with AI",
        "no_questions_yet": "This certification has no questions yet. Add some via the Admin Dashboard, "
                             "or switch to 'Generate New with AI'.",
        "only_one_question": "Only 1 question available — it will be used as-is.",
        "num_questions_label": "Number of Questions",
        "ai_gen_intro": "A brand-new set of questions will be generated by your selected model and "
                         "saved to the local database before your exam begins.",
        "model_provider_settings": "🔧 Model Provider Settings",
        "bank_full_switch": "This certification's bank is already at the {cap}-question "
                             "cap. Switch to 'Use Existing Question Bank' or add a new certification.",
        "num_new_questions_label": "Number of NEW questions to generate",
        "tag_exam_set_label": "Tag as Exam Set #",
        "tag_exam_set_help": "Which practice-exam slot these newly generated questions are filed under.",
        "timed_mode_label": "Timed Mode",
        "timed_mode_help": "Impose a time limit on this practice attempt, mirroring real exam conditions.",
        "time_limit_label": "Time Limit (minutes)",
        "exam_in_progress_info": "Exam in progress. Submit or reset to change configuration.",
        "abandon_reset_button": "🔁 Abandon & Reset Exam",
        "generate_start_button": "🤖 Generate & Start Exam",
        "start_exam_button": "🚀 Start Exam",
        "select_model_first": "Please select or enter a model before generating.",
        "starting_generation": "Starting generation...",
        "progress_generated": "{done} / {total} generated...",
        "generating_exam_spinner": "Generating your exam with AI...",
        "generation_failed": "Generation failed: {detail}",
        "no_questions_returned": "No questions were returned by the model.",
        "generated_with_issues": "Generated {count} question(s), with {issues} issue(s) along the way.",

        # --- Home / not-started screen ---
        "welcome_body": (
            "Welcome! This tool lets you practice for AWS certification exams using a "
            "customizable question bank stored locally in SQLite.\n\n"
            "**How to begin:**\n"
            "1. Use the sidebar to choose your target certification.\n"
            "2. Pick how many questions you'd like to attempt.\n"
            "3. Optionally enable **Timed Mode** to simulate real exam pressure.\n"
            "4. Click **Start Exam**.\n\n---"
        ),
        "question_bank_overview": "Question Bank Overview",
        "qs_suffix": "{count} Qs",

        # --- Timer ---
        "time_up_autosubmit": "⏰ Time's up! Auto-submitting your exam.",
        "time_remaining_elapsed": "⏳ Time remaining: **{remaining}**  &nbsp;|&nbsp;  ⏱️ Time elapsed: **{elapsed}**",
        "time_elapsed_only": "⏱️ Time elapsed: **{elapsed}**",

        # --- In-progress exam screen ---
        "practice_exam_title": "{code} Practice Exam",
        "answered_progress": "{answered} / {total} answered",
        "question_number": "**Question {num}.** {text}",
        "select_answer_for": "Select an answer for Question {num}",
        "submit_exam_button": "✅ Submit Exam",
        "unanswered_warning": "You have {count} unanswered question(s): {list}. You may still submit — "
                               "unanswered questions will be marked incorrect.",

        # --- Results / review screen ---
        "results_title": "{code} — Results",
        "pass_banner": "### ✅ PASS — {pct:.1f}% (Required: {threshold:.0f}%)",
        "fail_banner": "### ❌ FAIL — {pct:.1f}% (Required: {threshold:.0f}%)",
        "metric_correct": "Correct",
        "metric_incorrect": "Incorrect",
        "metric_unanswered": "Unanswered",
        "metric_total": "Total",
        "metric_time_taken": "⏱️ Time Taken",
        "review_mode_header": "📝 Review Mode",
        "review_mode_caption": "Expand each question to see your answer versus the correct answer and the full rationale.",
        "question_expander": "Question {num}: {preview}...",
        "correct_answer_tag": "*(Correct Answer)*",
        "your_answer_tag": "*(Your Answer)*",
        "did_not_answer": "You did not answer this question.",
        "explanation_label": "**Explanation:** {text}",
        "domain_label": "Domain: {domain}",
        "start_new_exam_button": "🔁 Start a New Exam",

        # --- Admin dashboard: shell ---
        "admin_title": "🛠️ Admin Dashboard",
        "admin_caption": "Manage the question bank: review counts, add questions manually, or batch-import new exams.",
        "tab_overview": "📊 Overview",
        "tab_add_question": "➕ Add Question",
        "tab_batch_import": "📁 Batch Import",
        "tab_ai_generator": "🤖 AI Question Generator",
        "tab_add_cert": "🏷️ Add Certification",

        # --- Admin: overview ---
        "question_counts_header": "Question Counts per Certification",
        "col_code": "Code",
        "col_certification": "Certification",
        "col_level": "Level",
        "col_question_count": "Question Count",
        "col_max_bank_size": "Max Bank Size",
        "no_certs_init_db": "No certifications found. Run init_db.py to seed the database.",
        "dedup_header": "🧹 Deduplicate Database",
        "dedup_caption": "Scans every certification's question bank and removes near-duplicate questions "
                          "(≥{pct}% text-similarity to another question in the same bank), keeping the "
                          "earliest-added copy of each. New questions are already checked automatically "
                          "on the way in — use this to clean up anything that predates that check, or "
                          "that was imported before deduplication was enabled.",
        "dedup_button": "🧹 Scan & Remove Duplicates (All Certifications)",
        "dedup_scanning": "Scanning for near-duplicate questions...",
        "dedup_none_found": "No near-duplicate questions found. Your question bank is clean.",
        "dedup_removed_summary": "Removed {count} near-duplicate question(s) across all certifications.",
        "dedup_removed_line": "  • {code}: removed {removed}, kept {kept}",

        # --- Admin: manual add ---
        "add_question_header": "Add a New Question",
        "no_certs_init_first": "No certifications available. Initialize the database first.",
        "certification_label": "Certification",
        "exam_set_label": "Exam Set # (1-10)",
        "exam_set_help": "Which full-length practice exam this question belongs to.",
        "question_text_label": "Question Text",
        "option_a_label": "Option A",
        "option_b_label": "Option B",
        "option_c_label": "Option C",
        "option_d_label": "Option D",
        "correct_option_label": "Correct Option",
        "explanation_field_label": "Explanation / Rationale",
        "domain_optional_label": "Domain (optional)",
        "add_question_button": "Add Question",
        "question_added_success": "Question added to {code} (Exam Set {exam_number}).",
        "could_not_add_question": "Could not add question: {error}",

        # --- Admin: batch import ---
        "batch_import_header": "Batch Import Questions (CSV or JSON)",
        "batch_import_instructions": (
            "Upload a `.csv` or `.json` file containing multiple questions. Each record must "
            "include the following fields:\n\n"
            "`question_text, option_a, option_b, option_c, option_d, correct_option, explanation`\n\n"
            "Optional fields: `exam_number` (defaults to 1), `domain`."
        ),
        "target_cert_import_label": "Target Certification for this import",
        "upload_file_label": "Upload CSV or JSON",
        "parsed_records": "Parsed **{count}** record(s) from `{filename}`.",
        "preview_first_5": "Preview of first 5 records.",
        "confirm_import_button": "Confirm & Import",
        "imported_success": "Imported {count} question(s) into {code}.",
        "skipped_duplicates_info": "Skipped {count} row(s) as near-duplicates (≥{pct}% similar to an existing question).",
        "rows_failed_other": "{count} row(s) failed for other reasons:",
        "failed_to_parse": "Failed to parse file: {error}",

        # --- Admin: AI generator ---
        "ai_generator_subheader": "Dynamically Generate Questions with AI",
        "ai_generator_intro": (
            "Generate realistic, scenario-based practice questions on demand using "
            "Anthropic's cloud API, or a **local Ollama / Open WebUI** instance — no "
            "data leaves your machine with the local options. Each certification's "
            "question bank can hold up to **{cap} questions**, enough for roughly 10 "
            "full-length practice exams. Generated questions are saved to the local "
            "SQLite database immediately."
        ),
        "bank_size_caption": "Current bank size: **{current}** / {cap} (**{room}** slot(s) remaining)",
        "exam_set_tag_label": "Exam Set # (1-10) to tag these questions with",
        "batch_size_label": "Batch size per model call",
        "batch_size_help": "Larger batches are faster but slightly more likely to hit output limits, "
                            "especially on smaller local models.",
        "bank_already_full": "This certification's question bank is already full.",
        "num_to_generate_label": "Number of questions to generate",
        "approx_calls_caption": "This will make approximately {count} model call(s).",
        "generate_button": "🚀 Generate Questions",
        "done_progress": "Done.",
        "generating_via_spinner": "Generating questions via {provider}...",
        "inserted_success": "Inserted {inserted} new question(s) into {code} across {batches} batch(es). Saved to the local database.",
        "skipped_dup_info": "Skipped {count} likely-duplicate question(s).",
        "issues_encountered": "{count} issue(s) encountered:",

        # --- Admin: add certification ---
        "add_cert_header": "Add a New Certification",
        "add_cert_caption": "Not just the five built-in AWS certifications — add any certification you'd "
                             "like to build a question bank for. It will immediately appear in the exam "
                             "selection dropdown.",
        "cert_code_label": "Certification Code",
        "cert_code_help": "Short unique identifier: letters, numbers, and hyphens only.",
        "cert_name_label": "Full Certification Name",
        "level_label": "Level",
        "pass_threshold_label": "Pass Threshold (%)",
        "add_cert_button": "Add Certification",
        "cert_added_success": "Added certification '{name}' ({code}). It now appears in the exam "
                               "dropdown — add questions to it via the tabs above.",
        "could_not_add_cert": "Could not add certification: {error}",

        # --- AI provider selector (shared) ---
        "model_provider_label": "Model Provider",
        "model_provider_help": "Use Anthropic's cloud API, or point at a local Ollama or Open WebUI instance.",
        "base_url_label": "Base URL",
        "base_url_help": "Address of your local Ollama / Open WebUI server.",
        "api_key_label": "API Key",
        "api_key_env_hint": " (ANTHROPIC_API_KEY is set in the environment — leave blank to use it)",
        "advanced_custom_path": "⚙️ Advanced: Custom API Path",
        "custom_path_caption": "By default we auto-try common Open WebUI chat-completions paths. If your "
                                "instance uses a nonstandard layout, or auto-detection fails, set the exact "
                                "path here (e.g. `/api/chat/completions`).",
        "custom_path_label": "Custom chat-completions path (optional)",
        "fetch_models_button": "🔄 Fetch Models",
        "fetching_models_spinner": "Fetching available models...",
        "no_models_returned": "No models were returned by this provider.",
        "model_label": "Model",
        "model_name_label": "Model name",
        "model_name_help": "Click 'Fetch Models' to list available models, or type one directly "
                            "(e.g. 'llama3:8b' for Ollama, 'claude-sonnet-5' for Anthropic).",
    },
    "ja": {
        # --- App / navigation ---
        "app_title": "☁️ AWS模擬試験エンジン",
        "nav_label": "ナビゲーション",
        "nav_help": "試験の演習と問題バンクの管理を切り替えます。",
        "nav_take_exam": "試験を受ける",
        "nav_admin": "管理ダッシュボード",
        "language_label": "🌐 言語",

        # --- Exam configuration sidebar ---
        "exam_config_header": "試験設定",
        "no_certs_found": "データベースに認定資格が見つかりません。",
        "target_cert_label": "対象の認定資格",
        "level_pass_mark": "レベル: **{level}** | 合格ライン: **{pct}%**",
        "questions_in_bank": "問題バンクの利用可能数: **{count}**",
        "question_source_header": "**問題のソース**",
        "question_source_bank": "📚 既存の問題バンクを使用",
        "question_source_ai": "🤖 AIで新規生成",
        "no_questions_yet": "この認定資格にはまだ問題がありません。管理ダッシュボードから追加するか、"
                             "「AIで新規生成」に切り替えてください。",
        "only_one_question": "利用可能な問題は1問のみです。そのまま使用されます。",
        "num_questions_label": "出題数",
        "ai_gen_intro": "選択したモデルによって新しい問題セットが生成され、試験開始前にローカルデータベースに保存されます。",
        "model_provider_settings": "🔧 モデルプロバイダー設定",
        "bank_full_switch": "この認定資格の問題バンクはすでに上限の{cap}問に達しています。"
                             "「既存の問題バンクを使用」に切り替えるか、新しい認定資格を追加してください。",
        "num_new_questions_label": "新規生成する問題数",
        "tag_exam_set_label": "試験セット番号を指定",
        "tag_exam_set_help": "新しく生成された問題をどの模擬試験セットに分類するかを指定します。",
        "timed_mode_label": "タイムモード",
        "timed_mode_help": "本番の試験に近い形で時間制限を設けます。",
        "time_limit_label": "制限時間（分）",
        "exam_in_progress_info": "試験実施中です。設定を変更するには提出するかリセットしてください。",
        "abandon_reset_button": "🔁 試験を中断してリセット",
        "generate_start_button": "🤖 生成して試験開始",
        "start_exam_button": "🚀 試験開始",
        "select_model_first": "生成前にモデルを選択または入力してください。",
        "starting_generation": "生成を開始しています...",
        "progress_generated": "{done} / {total} 件生成済み...",
        "generating_exam_spinner": "AIで試験問題を生成しています...",
        "generation_failed": "生成に失敗しました: {detail}",
        "no_questions_returned": "モデルから問題が返されませんでした。",
        "generated_with_issues": "{count}問を生成しましたが、{issues}件の問題が発生しました。",

        # --- Home / not-started screen ---
        "welcome_body": (
            "ようこそ！このツールでは、ローカルのSQLiteに保存されたカスタマイズ可能な問題バンクを使って、"
            "AWS認定資格試験の演習ができます。\n\n"
            "**始め方:**\n"
            "1. サイドバーで対象の認定資格を選択します。\n"
            "2. 挑戦する問題数を選びます。\n"
            "3. 必要に応じて**タイムモード**を有効にし、本番の緊張感を再現します。\n"
            "4. **試験開始**をクリックします。\n\n---"
        ),
        "question_bank_overview": "問題バンクの概要",
        "qs_suffix": "{count}問",

        # --- Timer ---
        "time_up_autosubmit": "⏰ 時間切れです！試験を自動的に提出します。",
        "time_remaining_elapsed": "⏳ 残り時間: **{remaining}**  &nbsp;|&nbsp;  ⏱️ 経過時間: **{elapsed}**",
        "time_elapsed_only": "⏱️ 経過時間: **{elapsed}**",

        # --- In-progress exam screen ---
        "practice_exam_title": "{code} 模擬試験",
        "answered_progress": "{answered} / {total} 問回答済み",
        "question_number": "**問題 {num}.** {text}",
        "select_answer_for": "問題{num}の回答を選択してください",
        "submit_exam_button": "✅ 試験を提出",
        "unanswered_warning": "未回答の問題が{count}問あります: {list}。そのまま提出することもできますが、"
                               "未回答の問題は不正解として扱われます。",

        # --- Results / review screen ---
        "results_title": "{code} — 結果",
        "pass_banner": "### ✅ 合格 — {pct:.1f}%（必要合格ライン: {threshold:.0f}%）",
        "fail_banner": "### ❌ 不合格 — {pct:.1f}%（必要合格ライン: {threshold:.0f}%）",
        "metric_correct": "正解",
        "metric_incorrect": "不正解",
        "metric_unanswered": "未回答",
        "metric_total": "合計",
        "metric_time_taken": "⏱️ 所要時間",
        "review_mode_header": "📝 復習モード",
        "review_mode_caption": "各問題を展開すると、あなたの回答と正解、詳しい解説を確認できます。",
        "question_expander": "問題{num}: {preview}...",
        "correct_answer_tag": "*(正解)*",
        "your_answer_tag": "*(あなたの回答)*",
        "did_not_answer": "この問題は未回答です。",
        "explanation_label": "**解説:** {text}",
        "domain_label": "分野: {domain}",
        "start_new_exam_button": "🔁 新しい試験を開始",

        # --- Admin dashboard: shell ---
        "admin_title": "🛠️ 管理ダッシュボード",
        "admin_caption": "問題バンクの管理:件数の確認、問題の手動追加、または一括インポートを行います。",
        "tab_overview": "📊 概要",
        "tab_add_question": "➕ 問題を追加",
        "tab_batch_import": "📁 一括インポート",
        "tab_ai_generator": "🤖 AI問題ジェネレーター",
        "tab_add_cert": "🏷️ 認定資格を追加",

        # --- Admin: overview ---
        "question_counts_header": "認定資格ごとの問題数",
        "col_code": "コード",
        "col_certification": "認定資格",
        "col_level": "レベル",
        "col_question_count": "問題数",
        "col_max_bank_size": "最大バンクサイズ",
        "no_certs_init_db": "認定資格が見つかりません。init_db.pyを実行してデータベースを初期化してください。",
        "dedup_header": "🧹 データベースの重複排除",
        "dedup_caption": "各認定資格の問題バンクをスキャンし、類似度が{pct}%以上の重複問題を検出して、"
                          "最初に追加されたものを残して削除します。新規追加時は自動的にチェックされるため、"
                          "この機能はチェック導入前や重複排除機能が有効になる前にインポートされたデータを"
                          "整理する際にお使いください。",
        "dedup_button": "🧹 全認定資格の重複をスキャンして削除",
        "dedup_scanning": "類似問題をスキャンしています...",
        "dedup_none_found": "重複する問題は見つかりませんでした。問題バンクはクリーンです。",
        "dedup_removed_summary": "全認定資格から{count}件の重複問題を削除しました。",
        "dedup_removed_line": "  • {code}: {removed}件削除、{kept}件保持",

        # --- Admin: manual add ---
        "add_question_header": "新しい問題を追加",
        "no_certs_init_first": "利用可能な認定資格がありません。まずデータベースを初期化してください。",
        "certification_label": "認定資格",
        "exam_set_label": "試験セット番号 (1-10)",
        "exam_set_help": "この問題がどの模擬試験セットに属するかを指定します。",
        "question_text_label": "問題文",
        "option_a_label": "選択肢 A",
        "option_b_label": "選択肢 B",
        "option_c_label": "選択肢 C",
        "option_d_label": "選択肢 D",
        "correct_option_label": "正解の選択肢",
        "explanation_field_label": "解説 / 根拠",
        "domain_optional_label": "分野（任意）",
        "add_question_button": "問題を追加",
        "question_added_success": "{code}（試験セット{exam_number}）に問題を追加しました。",
        "could_not_add_question": "問題を追加できませんでした: {error}",

        # --- Admin: batch import ---
        "batch_import_header": "問題の一括インポート（CSVまたはJSON）",
        "batch_import_instructions": (
            "複数の問題を含む`.csv`または`.json`ファイルをアップロードしてください。"
            "各レコードには以下のフィールドが必要です:\n\n"
            "`question_text, option_a, option_b, option_c, option_d, correct_option, explanation`\n\n"
            "任意フィールド: `exam_number`（デフォルトは1）, `domain`。"
        ),
        "target_cert_import_label": "このインポートの対象認定資格",
        "upload_file_label": "CSVまたはJSONをアップロード",
        "parsed_records": "`{filename}`から**{count}**件のレコードを読み取りました。",
        "preview_first_5": "最初の5件のプレビュー。",
        "confirm_import_button": "確認してインポート",
        "imported_success": "{code}に{count}件の問題をインポートしました。",
        "skipped_duplicates_info": "類似度{pct}%以上の重複として{count}件をスキップしました。",
        "rows_failed_other": "その他の理由で{count}件が失敗しました:",
        "failed_to_parse": "ファイルの解析に失敗しました: {error}",

        # --- Admin: AI generator ---
        "ai_generator_subheader": "AIで問題を動的に生成",
        "ai_generator_intro": (
            "Anthropicのクラウドapi、またはローカルの**Ollama / Open WebUI**インスタンスを使用して、"
            "リアルなシナリオベースの練習問題をオンデマンドで生成できます — "
            "ローカルオプションを使えばデータが外部に出ることはありません。"
            "各認定資格の問題バンクは最大**{cap}問**まで保持でき、フル模擬試験約10回分に相当します。"
            "生成された問題は即座にローカルのSQLiteデータベースに保存されます。"
        ),
        "bank_size_caption": "現在のバンクサイズ: **{current}** / {cap} （残り**{room}**枠）",
        "exam_set_tag_label": "これらの問題にタグ付けする試験セット番号 (1-10)",
        "batch_size_label": "モデル呼び出しごとのバッチサイズ",
        "batch_size_help": "バッチサイズが大きいほど高速ですが、特に小規模なローカルモデルでは"
                            "出力上限に達しやすくなります。",
        "bank_already_full": "この認定資格の問題バンクはすでに満杯です。",
        "num_to_generate_label": "生成する問題数",
        "approx_calls_caption": "約{count}回のモデル呼び出しが行われます。",
        "generate_button": "🚀 問題を生成",
        "done_progress": "完了しました。",
        "generating_via_spinner": "{provider}経由で問題を生成しています...",
        "inserted_success": "{code}に{inserted}件の新しい問題を{batches}バッチで追加しました。"
                             "ローカルデータベースに保存済みです。",
        "skipped_dup_info": "重複の可能性がある{count}件をスキップしました。",
        "issues_encountered": "{count}件の問題が発生しました:",

        # --- Admin: add certification ---
        "add_cert_header": "新しい認定資格を追加",
        "add_cert_caption": "組み込みの5つのAWS認定資格だけでなく、任意の認定資格の問題バンクを"
                             "構築できます。追加するとすぐに試験選択のドロップダウンに表示されます。",
        "cert_code_label": "認定資格コード",
        "cert_code_help": "簡潔で一意な識別子（英数字とハイフンのみ）。",
        "cert_name_label": "認定資格の正式名称",
        "level_label": "レベル",
        "pass_threshold_label": "合格ライン（%）",
        "add_cert_button": "認定資格を追加",
        "cert_added_success": "認定資格「{name}」（{code}）を追加しました。試験選択のドロップダウンに"
                               "表示されます — 上のタブから問題を追加してください。",
        "could_not_add_cert": "認定資格を追加できませんでした: {error}",

        # --- AI provider selector (shared) ---
        "model_provider_label": "モデルプロバイダー",
        "model_provider_help": "Anthropicのクラウドapiを使用するか、ローカルのOllamaまたはOpen WebUIインスタンスを指定します。",
        "base_url_label": "ベースURL",
        "base_url_help": "ローカルのOllama / Open WebUIサーバーのアドレス。",
        "api_key_label": "APIキー",
        "api_key_env_hint": "（環境変数ANTHROPIC_API_KEYが設定されています — 使用する場合は空欄のままにしてください）",
        "advanced_custom_path": "⚙️ 詳細設定: カスタムAPIパス",
        "custom_path_caption": "デフォルトでは一般的なOpen WebUIのチャット補完パスを自動的に試します。"
                                "お使いのインスタンスが独自のパス構成の場合や自動検出が失敗する場合は、"
                                "正確なパスをここに指定してください（例: `/api/chat/completions`）。",
        "custom_path_label": "カスタムチャット補完パス（任意）",
        "fetch_models_button": "🔄 モデルを取得",
        "fetching_models_spinner": "利用可能なモデルを取得しています...",
        "no_models_returned": "このプロバイダーからモデルが返されませんでした。",
        "model_label": "モデル",
        "model_name_label": "モデル名",
        "model_name_help": "「モデルを取得」をクリックして利用可能なモデルを一覧表示するか、"
                            "直接入力してください（例: Ollamaの場合は「llama3:8b」、"
                            "Anthropicの場合は「claude-sonnet-5」）。",
    },
}


def t(key: str, **kwargs) -> str:
    """
    Translate `key` into the currently selected UI language (st.session_state.language,
    defaulting to English). Falls back to English, then to the raw key, if missing.
    Any kwargs are used to .format() the resulting template.
    """
    lang = st.session_state.get("language", DEFAULT_LANGUAGE)
    template = TRANSLATIONS.get(lang, {}).get(key)
    if template is None:
        template = TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key)
    if kwargs:
        try:
            return template.format(**kwargs)
        except (KeyError, IndexError):
            return template
    return template
